@url = http://localhost:3001/users

###CRIAR
POST {{url}}
Content-Type: application/json

{
    "name": "Juca",
    "email": "j@gmail.com",
    "password": "1234",
    "birth": "2000-01-01"
}

### GET ALL
GET {{url}}
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjhmMTgzMWJjZDgzZjBlNDUxZWRkNyIsImlhdCI6MTcxNjk0NjEwNywiZXhwIjoxNzE2OTQ5NzA3fQ.rMJaik2QozX_Dvq_j9ov7aT73F48LdwcmYceJgEfKns" 


### GET BY ID
GET {{url}}/6628f1831bcd83f0e451edd7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjhmMTgzMWJjZDgzZjBlNDUxZWRkNyIsImlhdCI6MTcxNjk0NTM2MywiZXhwIjoxNzE2OTQ4OTYzfQ.-aCMOHMuz5V4yz6RfwYNVBWkHmvkiFkOCap4y16wo7A

